"""Create Lotto Draw Model

Revision ID: 35f38214ca8f
Revises: 
Create Date: 2023-04-24 02:35:04.470265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f38214ca8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto_draw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('A', sa.String(), nullable=False),
    sa.Column('B', sa.String(), nullable=False),
    sa.Column('C', sa.String(), nullable=False),
    sa.Column('D', sa.String(), nullable=False),
    sa.Column('E', sa.String(), nullable=False),
    sa.Column('J', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotto_draw_id'), 'lotto_draw', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lotto_draw_id'), table_name='lotto_draw')
    op.drop_table('lotto_draw')
    # ### end Alembic commands ###
