"""Lotto Draw and types

Revision ID: 969c3033696a
Revises: 
Create Date: 2023-04-30 21:52:23.785335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969c3033696a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotto_type_name'), 'lotto_type', ['name'], unique=True)
    op.create_table('winning_draw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('A', sa.SmallInteger(), nullable=False),
    sa.Column('B', sa.SmallInteger(), nullable=False),
    sa.Column('C', sa.SmallInteger(), nullable=False),
    sa.Column('D', sa.SmallInteger(), nullable=False),
    sa.Column('E', sa.SmallInteger(), nullable=False),
    sa.Column('J', sa.SmallInteger(), nullable=False),
    sa.Column('lotto_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['lotto_type_id'], ['lotto_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winning_draw_A'), 'winning_draw', ['A'], unique=False)
    op.create_index(op.f('ix_winning_draw_B'), 'winning_draw', ['B'], unique=False)
    op.create_index(op.f('ix_winning_draw_C'), 'winning_draw', ['C'], unique=False)
    op.create_index(op.f('ix_winning_draw_D'), 'winning_draw', ['D'], unique=False)
    op.create_index(op.f('ix_winning_draw_E'), 'winning_draw', ['E'], unique=False)
    op.create_index(op.f('ix_winning_draw_J'), 'winning_draw', ['J'], unique=False)
    op.create_index(op.f('ix_winning_draw_draw_date'), 'winning_draw', ['draw_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winning_draw_draw_date'), table_name='winning_draw')
    op.drop_index(op.f('ix_winning_draw_J'), table_name='winning_draw')
    op.drop_index(op.f('ix_winning_draw_E'), table_name='winning_draw')
    op.drop_index(op.f('ix_winning_draw_D'), table_name='winning_draw')
    op.drop_index(op.f('ix_winning_draw_C'), table_name='winning_draw')
    op.drop_index(op.f('ix_winning_draw_B'), table_name='winning_draw')
    op.drop_index(op.f('ix_winning_draw_A'), table_name='winning_draw')
    op.drop_table('winning_draw')
    op.drop_index(op.f('ix_lotto_type_name'), table_name='lotto_type')
    op.drop_table('lotto_type')
    # ### end Alembic commands ###
